### PR TITLE
Replace closebrackets and matchbrackets with parinfer

### PR DESCRIPTION
**Pull request by urzae**
This adds [parinfer](https://github.com/shaunlebron/parinfer) to the editor in the sketches section of quil-site. Parinfer replaces functionality previously provided by the closebrackets and matchbrackets plugins and extends beyond what they provided.

Since the automated compress service on the codemirror page does not work anymore, the minified and packed js file is replaced by its uncompressed constituents to replace the editor plugins. 

To integrate [parinfer](https://github.com/shaunlebron/parinfer) in [CodeMirror](https://codemirror.net/), the official plugin [parinfer-codemirror](https://github.com/shaunlebron/parinfer-codemirror) is used.

### CODE REVIEW

**Comment by nbeloglazov** [comment]
Thanks for improving the editor! One request is that we should use minified versions of all JS. Do you know if it's possible to get minified for all JS files you adding? If not we probably could minify them ourselves.

**Comment by urzae** [comment]
I have not found minified versions of all used files, so I minified and packed them using [uglifyjs](https://www.npmjs.com/package/uglify-js):
`uglifyjs codemirror-5.12.js codemirror-5.12_clojure.js codemirror-5.12_lint.js parinfer.js parinfer-codemirror.js -o codemirror-5.12_clojure_lint_parinfer.min.js -c -m`

Another option would be a leiningen plugin or including them in the compiled files (`:libs` or `:foreign-libs` in the `:cljsbuild` section of project.clj.

**Comment by nbeloglazov** [comment]
Just tried it - I like that it keeps balance of brackets, but it doesn't seem to be highlighting matching bracket. Currently on [quil.info](http://quil.info/sketches/create) bracket under cursor and its matching bracket highlighted in green. When I check http://shaunlebron.github.io/parinfer/ I see that it highlights matching brackets as well. Is there an issue of integration between codemirror and parinfer?

**Comment by urzae** [comment]
Different from what I first assumed, [http://shaunlebron.github.io/parinfer/ ](http://shaunlebron.github.io/parinfer/) uses the addon matchbrackets to highlight matching brackets, and the functionality is not part of parinfer itself. 
Therefore I added it again.

**Comment by nbeloglazov** [comment]
Great, thanks for figuring it out!

**Pull request merged**
