### PR TITLE
Add 'matrix' sketch.

### PR DESCRIPTION
**Pull request by namenu**
http://quil.info/sketches/show/-L46cDxm6sey89kNxe5u

Found 'equilibrium' from examples so I sketched this.

### CODE REVIEW

**Comment by nbeloglazov** [comment]
Wow, looks great! I'll merge it later. What do the falling characters mean? Or they just "letters" without any specific meaning?

**Comment by namenu** [comment]
Thanks @nbeloglazov. Quil was really fun to play with!
Following texts are not even a gibberish. They're Just random combiniations of [Japanese charecters](https://en.wikipedia.org/wiki/Katakana).
I have chosen them because they look more like cyberpunkish(?).

**Comment by nbeloglazov** [comment]
Hey. I tried running this sketch on linux but it didn't work. Apparently, I don't have font characters for Katakana. I tried loading a font but failed to do so. So either I have to switch to Latin (or other more wide-spread characters) or somehow load a font. What do you think?

**Comment by namenu** [comment]
@nbeloglazov I've tested with Latin characters but it was not interesting anymore.
So I change to use system-wide `serif` font for rendering.
Not tested on Linux yet, so I'll let you know when availability is confirmed.

**Comment by nbeloglazov** [comment]
I found the problem. It was here: 
```clojure
(q/text c (:x raindrop) y glyph-size (q/height))
```
The third parameter is `glyph-size` which says that width of area is 12. When processing.js gets this call it calculates width of character to draw and it's something like 12.0123 and it decides to drop this character because it won't fit in 12px wide box. So the fix is not to provide glyph-size and q/height at all. I'll fix it.

**Comment by nbeloglazov** [comment]
Deployed the new version: http://quil.info/?example=matrix Also I merged using command line so I'm going to close it this pull request without "merging". Thanks a lot for the sketch!

**Pull request closed without merging**
